(G-CODE GENERATED BY FLATCAM v8.993 - www.flatcam.org - Version Date: 2020/06/05)

(Name: MainBoardSplit-PTH.Mount.drl_cnc_1)
(Type: G-code from Excellon)
(Units: MM)

(Created on Sunday, 01 November 2020 at 06:15)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 1.0007599999999999)
(Tool: 2 -> Dia: 2.1996399999999996)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 50.0)
(Tool: 2 -> Feedrate: 50.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -2.0)
(Tool: 2 -> Z_Cut: -2.0)

(Tools Offset: )
(Tool: 2 -> Offset Z: -0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 1.0)
(Tool: 2 -> Z_Move: 1.0)

(Z Start: None mm)
(Z End: 2.0 mm)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:    2.5476 ...   30.9804  mm)
(Y range:    3.0556 ...   20.3124  mm)

(Spindle Speed: 2000.0 RPM)
G21
G90
G94



G00 Z1.0000

G01 F50.00
M03 S2000
G00 X16.5735 Y11.4935
G01 Z-2.0000
G01 Z0
G00 Z1.0000
M05
G00 Z2.00

G01 X0Y0 F300